export const ACTIONS ={
    FETCH_USER_DATA_INIT: "FETCH_USER_DATA_INIT",
    FETCH_USER_DATA_SUCCESS: "FETCH_USER_DATA_SUCCESS",
    FETCH_USER_DATA_FAILURE: "FETCH_USER_DATA_FAILURE",
    RESET_USER_DATA: "RESET_USER_DATA",
}